### ISSUE TITLE
writePython3Bin flake8 workaround

### ISSUE THREAD

**Issue by ghtau** [mcdonc/.nixconfig#1]
https://github.com/mcdonc/.nixconfig/blob/833a3ec72e027fa917721a2ddb686d69c9b23a08/videos/writepy3/script.rst?plain=1#L36-L43

One workaround is to add `# flake8: noqa` to the script as described [here](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#ignoring-entire-files).

E.g.
```
mypyscript = pkgs.writers.writePython3Bin "mypyscript" {} ''
  # flake8: noqa
  print("hello from a Python script")#a comment
'';
```

**Comment by mcdonc** [comment]
Awesome!  Thanks.
