### ISSUE TITLE
chown instead of chmod /var/lib/syncoid/backup.key

### ISSUE THREAD

**Issue by fschn90** [mcdonc/.nixconfig#3]
Hello, 

thanks a lot for your videos. 

in [NixOS 59: Remote ZFS Backups Over SSH Using Syncoid](https://github.com/mcdonc/.nixconfig/blob/master/videos/zfsremotebackups/script.rst#nixos-59-remote-zfs-backups-over-ssh-using-syncoid) for this part:

```bash
$ sudo cp /home/chrism/backup.key /var/lib/syncoid
$ sudo chmod o+r /var/lib/syncoid/backup.key
```

i got following error message:

```bash 
Permissions are too open.
It is recommended that your private key files are NOT accessible by others.
This private key will be ignored.
```

instead, i did:

```bash
$ sudo cp /home/chrism/backup.key /var/lib/syncoid
$ sudo chwon syncoid:syncoid /var/lib/syncoid/backup.key
```

and it works like a charm!

**Comment by mcdonc** [comment]
Thanks!
